version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: perspectiva_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - perspectiva_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/articles"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: perspectiva_frontend
    restart: unless-stopped
    ports:
      - "8080:3000"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/.env.docker
    networks:
      - perspectiva_net

networks:
  perspectiva_net:
    driver: bridge
